theme: jekyll-theme-minimal
title: William Nicholas
description: I'm a graduate student in Indiana University's top-ranked Master of Public Affairs program, where I focus on data science for public administration. Over my career, I've developed a professional interest in the application of data-driven technologies to equitably solve environmental and logistical challenges at scale. Currently, I'm working on personal data research.
